plugin_repo(
    name = "python",
    owner = "please-build",
    plugin = "python-rules",
    revision = "v1.4.1",
)
plugin_repo(
  name = "docker",
  revision = "v0.1.0",
  plugin = "docker-rules",
  owner = "please-build",
)
plugin_repo(
  name = "shell",
  revision = "v0.2.0",
  plugin = "shell-rules",
  owner = "please-build",
)
